In [2]:
from PIL import Image,ImageOps
from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder

In [3]:
df=read_csv('breast-cancer-wisconsin.data')

In [4]:
df.head()

id   clump_thickness   unif_cell_size   unif_cell_shape  \
0  1000025                 5                1                 1   
1  1002945                 5                4                 4   
2  1015425                 3                1                 1   
3  1016277                 6                8                 8   
4  1017023                 4                1                 1   

    marg_adhesion   single_epith_cell_size  bare_nulei   bland_chrom  \
0               1                        2           1             3   
1               5                        7          10             3   
2               1                        2           2             3   
3               1                        3           4             3   
4               3                        2           1             3   

    norm_nucleoli   mitoses   class  
0               1         1       2  
1               2         1       2  
2               1         1       2  
3               7         1       2  
4               1         1       2

In [5]:
df=df.drop(['id'],axis=1)
df

clump_thickness   unif_cell_size   unif_cell_shape   marg_adhesion  \
0                   5                1                 1               1   
1                   5                4                 4               5   
2                   3                1                 1               1   
3                   6                8                 8               1   
4                   4                1                 1               3   
..                ...              ...               ...             ...   
694                 3                1                 1               1   
695                 2                1                 1               1   
696                 5               10                10               3   
697                 4                8                 6               4   
698                 4                8                 8               5   

      single_epith_cell_size  bare_nulei   bland_chrom   norm_nucleoli  \
0                          2           1             3               1   
1                          7          10             3               2   
2                          2           2             3               1   
3                          3           4             3               7   
4                          2           1             3               1   
..                       ...         ...           ...             ...   
694                        3           2             1               1   
695                        2           1             1               1   
696                        7           3             8              10   
697                        3           4            10               6   
698                        4           5            10               4   

      mitoses   class  
0           1       2  
1           1       2  
2           1       2  
3           1       2  
4           1       2  
..        ...     ...  
694         1       2  
695         1       2  
696         2       4  
697         1       4  
698         1       4  

[699 rows x 10 columns]

In [6]:
df=df[df[' bare_nulei'] != '?']

In [7]:
x=df.iloc[: , 0:9]
y=df.iloc[: ,  9]

In [8]:
x

clump_thickness   unif_cell_size   unif_cell_shape   marg_adhesion  \
0                   5                1                 1               1   
1                   5                4                 4               5   
2                   3                1                 1               1   
3                   6                8                 8               1   
4                   4                1                 1               3   
..                ...              ...               ...             ...   
694                 3                1                 1               1   
695                 2                1                 1               1   
696                 5               10                10               3   
697                 4                8                 6               4   
698                 4                8                 8               5   

      single_epith_cell_size  bare_nulei   bland_chrom   norm_nucleoli  \
0                          2           1             3               1   
1                          7          10             3               2   
2                          2           2             3               1   
3                          3           4             3               7   
4                          2           1             3               1   
..                       ...         ...           ...             ...   
694                        3           2             1               1   
695                        2           1             1               1   
696                        7           3             8              10   
697                        3           4            10               6   
698                        4           5            10               4   

      mitoses  
0           1  
1           1  
2           1  
3           1  
4           1  
..        ...  
694         1  
695         1  
696         2  
697         1  
698         1  

[683 rows x 9 columns]

Logistic Regression

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=393)

In [10]:
from sklearn.linear_model import LogisticRegression
l=LogisticRegression()

In [11]:
l.fit(x_train,y_train)

LogisticRegression()

In [12]:
l.score(x_train,y_train)

0.9615384615384616

In [13]:
l.score(x_test,y_test) # YES, AGAIN IT'S A PERFECT MODEL. WOW!!!!!!!!

1.0

In [14]:
l.predict([[4,2,1,1,1,2,3,2,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [15]:
l.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

S  V  C

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [17]:
from sklearn.svm import SVC
s=SVC(kernel='poly')             
s.fit(x_train,y_train)

SVC(kernel='poly')

In [18]:
s.score(x_train,y_train)

0.9743589743589743

In [19]:
s.score(x_test,y_test)       # 99% accuracy coool!

0.9927007299270073

In [20]:
l.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [21]:
l.predict([[4,2,1,1,1,2,3,2,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

........................................................................

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=129)

In [23]:
from sklearn.svm import SVC
s=SVC(kernel='linear')             
s.fit(x_train,y_train)

SVC(kernel='linear')

In [24]:
s.score(x_train,y_train)

0.967032967032967

In [25]:
s.score(x_test,y_test)   # poly better fits here.

1.0

In [26]:
s.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

GAUSSIAN NAIVE BIAS

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [66]:
from sklearn.naive_bayes import GaussianNB
n=GaussianNB()
n.fit(x_train,y_train)

GaussianNB()

In [67]:
n.score(x_train,y_train)

0.9505494505494505

In [68]:
n.score(x_test,y_test)

1.0

KNN CLASSIFIER

In [27]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier(n_neighbors=3)
k.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [28]:
k.score(x_train,y_train)

0.9798534798534798

In [29]:
k.score(x_test,y_test)

0.9854014598540146

In [30]:
k.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [31]:
scores=[]
for k in range(1,20):
    z=KNeighborsClassifier(n_neighbors=k)
    z.fit(x_train,y_train)
    accuracy1=z.score(x_train,y_train)
    accuracy2=z.score(x_test,y_test)
    scores.append(accuracy1)
    scores.append(accuracy2)
    print('\nk=%d accuracy=%.2f' % (k, accuracy1*100))
    print('\nk=%d accuracy=%.2f' % (k, accuracy2*100))


k=1 accuracy=100.00

k=1 accuracy=97.81

k=2 accuracy=97.44

k=2 accuracy=95.62

k=3 accuracy=97.99

k=3 accuracy=98.54

k=4 accuracy=97.62

k=4 accuracy=99.27

k=5 accuracy=98.17

k=5 accuracy=99.27

k=6 accuracy=97.99

k=6 accuracy=100.00

k=7 accuracy=97.80

k=7 accuracy=100.00

k=8 accuracy=97.25

k=8 accuracy=99.27

k=9 accuracy=96.89

k=9 accuracy=99.27

k=10 accuracy=96.52

k=10 accuracy=99.27

k=11 accuracy=96.70

k=11 accuracy=99.27

k=12 accuracy=96.15

k=12 accuracy=99.27

k=13 accuracy=95.97

k=13 accuracy=99.27

k=14 accuracy=95.97

k=14 accuracy=99.27

k=15 accuracy=96.15

k=15 accuracy=100.00

k=16 accuracy=96.15

k=16 accuracy=100.00

k=17 accuracy=95.97

k=17 accuracy=100.00

k=18 accuracy=96.15

k=18 accuracy=99.27

k=19 accuracy=96.15

k=19 accuracy=100.00


RF CLASSIFIER

In [32]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(n_estimators=60,random_state=1)
r.fit(x_train,y_train)

RandomForestClassifier(n_estimators=60, random_state=1)

U may change n_estimators to 50 or 100, but it causes overfitting on train data

10 is best(99% accuracy)

In [33]:
r.score(x_train,y_train)

1.0

In [34]:
r.score(x_test,y_test)

0.9927007299270073

In [35]:
r.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

GRADIENT BOOSTING

In [48]:
from sklearn.ensemble import GradientBoostingClassifier
g=GradientBoostingClassifier(n_estimators=100,random_state=1)
g.fit(x_train,y_train)

GradientBoostingClassifier(random_state=1)

In [49]:
g.score(x_train,y_train)

1.0

In [50]:
g.score(x_test,y_test)

0.9781021897810219

In [39]:
g.predict([[8,10,10,8,7,10,9,7,1]])

c:\Users\debna\Downloads\Anaconda33\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

RF is best. Even better than Gradient Boosting

In [51]:
#RF model
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

max_train_accuracy = 0  # Initialize maximum training accuracy
max_test_accuracy = 0  # Initialize maximum test accuracy
best_random_state_train = 0
best_random_state_test = 0

for i in range(1, 100):  # Vary random state
    # Vary number of estimators
    d = GradientBoostingClassifier(random_state=i)
    d.fit(x_train, y_train)
    
    train_accuracy = d.score(x_train, y_train)  # Evaluate accuracy on training data
    test_accuracy = d.score(x_test, y_test)  # Evaluate accuracy on test data
    
    # Check and update best training accuracy and random state
    if train_accuracy > max_train_accuracy:
        max_train_accuracy = train_accuracy
        best_random_state_train = i
    
    # Check and update best test accuracy and random state
    if test_accuracy > max_test_accuracy:
        max_test_accuracy = test_accuracy
        best_random_state_test = i

print(f"Best Training Accuracy: {max_train_accuracy} achieved with random state: {best_random_state_train}")
print(f"Best Test Accuracy: {max_test_accuracy} achieved with random state: {best_random_state_test}")


Best Training Accuracy: 1.0 achieved with random state: 1
Best Test Accuracy: 0.9781021897810219 achieved with random state: 1


In [56]:
'''###
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=GaussianNB()
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

The maximum training accuracy within the range of random states is: 0.9761904761904762 achieved with random state: 176
The maximum testing accuracy within the range of random states is: 1.0 achieved with random state: 1


In [40]:
'''import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    l = LogisticRegression()  # Initialize your model here, for example, Logistic Regression
    l.fit(x_train, y_train)   # Train the model
    train_score = l.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = l.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'import numpy as np\nfrom sklearn.model_selection import train_test_split \nfrom sklearn.linear_model import LogisticRegression\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 1000):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)\n    l = LogisticRegression()  # Initialize your model here, for example, Logistic Regression\n    l.fit(x_train, y_train)   # Train the model\n    train_score = l.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = l.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum

In [41]:
'''###
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Assuming 'x' and 'y' are defined with your dataset

max_train_accuracy = 0.0  # Initialize maximum training accuracy
best_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy
max_test_accuracy = 0.0  # Initialize maximum testing accuracy
best_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy

for i in range(1, 500):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)
    r=SVC(kernel='linear')
    r.fit(x_train,y_train)  # Train the model
    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set
    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set
    
    # Check for the maximum training accuracy
    if train_score > max_train_accuracy:
        max_train_accuracy = train_score
        best_train_random_state = i

    # Check for the maximum testing accuracy
    if test_score > max_test_accuracy:
        max_test_accuracy = test_score
        best_test_random_state = i

print(f"The maximum training accuracy within the range of random states is: {max_train_accuracy} achieved with random state: {best_train_random_state}")
print(f"The maximum testing accuracy within the range of random states is: {max_test_accuracy} achieved with random state: {best_test_random_state}")
'''

'###\nimport numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC\n\n# Assuming \'x\' and \'y\' are defined with your dataset\n\nmax_train_accuracy = 0.0  # Initialize maximum training accuracy\nbest_train_random_state = 0  # Initialize variable to store the random state of the best training accuracy\nmax_test_accuracy = 0.0  # Initialize maximum testing accuracy\nbest_test_random_state = 0  # Initialize variable to store the random state of the best testing accuracy\n\nfor i in range(1, 500):\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=i)\n    r=SVC(kernel=\'linear\')\n    r.fit(x_train,y_train)  # Train the model\n    train_score = r.score(x_train, y_train)  # Calculate accuracy on the training set\n    test_score = r.score(x_test, y_test)  # Calculate accuracy on the test set\n    \n    # Check for the maximum training accuracy\n    if train_score > max_train_accuracy:\n        max_train_accurac