In [223]:
# Import required libraries
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [224]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [225]:
df=read_csv('JaipurFinalCleanData.csv')

In [226]:
df.columns

Index(['date', 'meantempm', 'maxtempm', 'mintempm', 'meantempm_1',
       'meantempm_2', 'meantempm_3', 'meandewptm_1', 'meandewptm_2',
       'meandewptm_3', 'meanpressurem_1', 'meanpressurem_2', 'meanpressurem_3',
       'maxhumidity_1', 'maxhumidity_2', 'maxhumidity_3', 'minhumidity_1',
       'minhumidity_2', 'minhumidity_3', 'maxtempm_1', 'maxtempm_2',
       'maxtempm_3', 'mintempm_1', 'mintempm_2', 'mintempm_3', 'maxdewptm_1',
       'maxdewptm_2', 'maxdewptm_3', 'mindewptm_1', 'mindewptm_2',
       'mindewptm_3', 'maxpressurem_1', 'maxpressurem_2', 'maxpressurem_3',
       'minpressurem_1', 'minpressurem_2', 'minpressurem_3', 'precipm_1',
       'precipm_2', 'precipm_3'],
      dtype='object')

In [227]:
df.head()

date  meantempm  maxtempm  mintempm  meantempm_1  meantempm_2  \
0  2016-05-04         34        41        27         35.0         36.0   
1  2016-05-05         31        38        24         34.0         35.0   
2  2016-05-06         28        34        21         31.0         34.0   
3  2016-05-07         30        38        23         28.0         31.0   
4  2016-05-08         34        41        26         30.0         28.0   

   meantempm_3  meandewptm_1  meandewptm_2  meandewptm_3  ...  mindewptm_3  \
0         34.0           6.0           4.0          -1.0  ...        -10.0   
1         36.0           7.0           6.0           4.0  ...         -2.0   
2         35.0          11.0           7.0           6.0  ...         -2.0   
3         34.0          13.0          11.0           7.0  ...          0.0   
4         31.0          10.0          13.0          11.0  ...          6.0   

   maxpressurem_1  maxpressurem_2  maxpressurem_3  minpressurem_1  \
0          1009.0          1008.0          1009.0          1000.0   
1          1008.0          1009.0          1008.0          1001.0   
2          1011.0          1008.0          1009.0          1003.0   
3          1011.0          1011.0          1008.0          1004.0   
4          1010.0          1011.0          1011.0          1002.0   

   minpressurem_2  minpressurem_3  precipm_1  precipm_2  precipm_3  
0          1001.0           999.0        0.0        0.0        0.0  
1          1000.0          1001.0        0.0        0.0        0.0  
2          1001.0          1000.0        5.0        0.0        0.0  
3          1003.0          1001.0        0.0        5.0        0.0  
4          1004.0          1003.0        0.0        0.0        5.0  

[5 rows x 40 columns]

In [228]:
df.isnull().sum()

date               0
meantempm          0
maxtempm           0
mintempm           0
meantempm_1        0
meantempm_2        0
meantempm_3        0
meandewptm_1       0
meandewptm_2       0
meandewptm_3       0
meanpressurem_1    0
meanpressurem_2    0
meanpressurem_3    0
maxhumidity_1      0
maxhumidity_2      0
maxhumidity_3      0
minhumidity_1      0
minhumidity_2      0
minhumidity_3      0
maxtempm_1         0
maxtempm_2         0
maxtempm_3         0
mintempm_1         0
mintempm_2         0
mintempm_3         0
maxdewptm_1        0
maxdewptm_2        0
maxdewptm_3        0
mindewptm_1        0
mindewptm_2        0
mindewptm_3        0
maxpressurem_1     0
maxpressurem_2     0
maxpressurem_3     0
minpressurem_1     0
minpressurem_2     0
minpressurem_3     0
precipm_1          0
precipm_2          0
precipm_3          0
dtype: int64

In [229]:
x=df.iloc[:,1:-1]

In [230]:
x.columns

Index(['meantempm', 'maxtempm', 'mintempm', 'meantempm_1', 'meantempm_2',
       'meantempm_3', 'meandewptm_1', 'meandewptm_2', 'meandewptm_3',
       'meanpressurem_1', 'meanpressurem_2', 'meanpressurem_3',
       'maxhumidity_1', 'maxhumidity_2', 'maxhumidity_3', 'minhumidity_1',
       'minhumidity_2', 'minhumidity_3', 'maxtempm_1', 'maxtempm_2',
       'maxtempm_3', 'mintempm_1', 'mintempm_2', 'mintempm_3', 'maxdewptm_1',
       'maxdewptm_2', 'maxdewptm_3', 'mindewptm_1', 'mindewptm_2',
       'mindewptm_3', 'maxpressurem_1', 'maxpressurem_2', 'maxpressurem_3',
       'minpressurem_1', 'minpressurem_2', 'minpressurem_3', 'precipm_1',
       'precipm_2'],
      dtype='object')

In [231]:
x.shape

(676, 38)

In [232]:
y=df[['precipm_3']]

In [233]:
y

precipm_3
0          0.0
1          0.0
2          0.0
3          0.0
4          5.0
..         ...
671        0.0
672        0.0
673        0.0
674        0.0
675        0.0

[676 rows x 1 columns]

In [234]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=128)

In [249]:
from sklearn.ensemble import RandomForestRegressor
r=RandomForestClassifier(n_estimators=500)

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode labels
y_train_encoded = label_encoder.fit_transform(y_train)

# Fit RandomForestClassifier with encoded labels
r.fit(x_train, y_train_encoded)


c:\Users\debna\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RandomForestClassifier(n_estimators=500)

In [250]:
r.score(x_train, y_train_encoded)

1.0

In [251]:
r.predict([[30,35,25,28.0,27.0,26.0,25.0,25.0,26.0,1003.69,1003.93,1002.31,100.0,100.0,100.0,49.0,69.0,82.0,34.0,31.0,28.0,23.0,23.0,24.0,26.0,26.0,27.0,23.0,23.0,24.0,1006.0,1006.0,1005.0,999.0,1001.0,998.0,0.0,0.0]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([28], dtype=int64)

In [252]:
r.predict([[28,34,23,27.0,26.0,26.0,25.0,26.0,26.0,1003.93,1002.31,1001.66,100.0,100.0,100.0,69.0,82.0,51.0,31.0,28.0,28.0,23.0,24.0,25.0,26.0,27.0,27.0,23.0,24.0,15.0,1006.0,1005.0,1003.0,1001.0,998.0,999.0,0.0,51.0]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([24], dtype=int64)

In [254]:
r.predict([[30,34,26,28.0,29.0,31.0,25.0,24.0,24.0,1000.34,999.24,998.09,94.0,89.0,94.0,66.0,40.0,37.0,31.0,35.0,37.0,26.0,23.0,25.0,27.0,25.0,26.0,23.0,22.0,21.0,1003.0,1001.0,1000.0,996.0,995.0,993.0,5.0,0.2]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [246]:
# Standardize the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Build the ANN model
model = Sequential()
model.add(Dense(units=512, activation='relu', input_dim=38))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train_scaled, y_train, epochs=15, batch_size=1, validation_data=(x_test_scaled, y_test))


Epoch 1/15


c:\Users\debna\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\debna\anaconda3\Lib\site-packages\keras\src\losses\losses.py:22: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(1, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


461/473 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8770 - loss: 0.0000e+00

c:\Users\debna\anaconda3\Lib\site-packages\keras\src\losses\losses.py:22: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(1, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


473/473 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8767 - loss: 0.0000e+00 - val_accuracy: 0.8128 - val_loss: 0.0000e+00
Epoch 2/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8448 - loss: 0.0000e+00 - val_accuracy: 0.8128 - val_loss: 0.0000e+00
Epoch 3/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8101 - loss: 0.0000e+00 - val_accuracy: 0.8177 - val_loss: 0.0000e+00
Epoch 4/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8399 - loss: 0.0000e+00 - val_accuracy: 0.8177 - val_loss: 0.0000e+00
Epoch 5/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8314 - loss: 0.0000e+00 - val_accuracy: 0.8177 - val_loss: 0.0000e+00
Epoch 6/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8277 - loss: 0.0000e+00 - val_accuracy: 0.8177 - val_loss: 0.0000e+00
Epoch 7/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8525 - loss: 0.0000e+00 - val_accuracy: 0.8177 - val_loss: 0.0000e+00
Epoch 8/15
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accur

In [247]:
import numpy as np

# Input data for prediction
input_data = np.array([[28,34,23,27.0,26.0,26.0,25.0,26.0,26.0,1003.93,1002.31,1001.66,100.0,100.0,100.0,69.0,82.0,51.0,31.0,28.0,28.0,23.0,24.0,25.0,26.0,27.0,27.0,23.0,24.0,15.0,1006.0,1005.0,1003.0,1001.0,998.0,999.0,0.0,51.0]])

# Standardize the input data using the same scaler used for training
input_data_scaled = scaler.transform(input_data)

# Make prediction for a single input
prediction = model.predict(input_data_scaled)[0]  # Get the first (and only) prediction

# Optionally, print the raw prediction
print("Raw Prediction:", prediction)

# Convert the prediction to a human-readable format if necessary
# Since it's regression, there's no need for decoding
predicted_temperature = prediction[0]  # Assuming prediction is a single value for temperature

# Print the predicted temperature
print("Predicted Mean Temperature:", predicted_temperature)


c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step
Raw Prediction: [1.]
Predicted Mean Temperature: 1.0


In [248]:
prediction

array([1.], dtype=float32)