In [273]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

1. CREATE INPUT LAYER

In [274]:
data=array([2,3])

In [275]:
x0=data[0]
x1=data[1]

In [276]:
in_layer=array([x0,x1])

In [277]:
in_layer

array([2, 3])

2. CREATE HIDDEN LAYER

In [278]:
weights={'x2':array([1,1]),
         'x3':array([-1,1]),
         'x4':array([2,-1])}

In [279]:
weights

{'x2': array([1, 1]), 'x3': array([-1,  1]), 'x4': array([ 2, -1])}

In [280]:
x2=(in_layer*weights['x2']).sum()

In [281]:
x3=(in_layer*weights['x3']).sum()

In [282]:
hidden_layer=array([x2,x3])
hidden_layer

array([5, 1])

3. CREATE OUTPUT LAYER

In [283]:
x4=(hidden_layer*weights['x4']).sum()

In [284]:
out_layer=array([x4])

In [285]:
out_layer

array([9])

...................WITH  ACTIVATION FUNCTION...........................

ASSIGN WEIGHTS

In [286]:
weights={'x2':array([1,1]),
         'x3':array([-1,1]),
         'x4':array([2,-1])}

AF - Relu

In [287]:
def relu(x):
    return max(0,x)

AF - Sigmoid

In [288]:
def sigmoid(x):
    if x<=0:
        return 0
    else:
        return 1
    

 INPUT LAYER

In [289]:
data=array([2,3])

In [290]:
data

array([2, 3])

In [291]:
x0=data[0]
x1=data[1]

In [292]:
in_layer=array([x0,x1])

In [293]:
in_layer

array([2, 3])

 HIDDEN  LAYER

In [294]:
x2=(in_layer*weights['x2']).sum()
x3=(in_layer*weights['x3']).sum()

In [295]:
x2=relu(x2)
x3=relu(x3)

In [296]:
hidden_layer=array([x2,x3])

In [297]:
hidden_layer

array([5, 1])

 since,    5  &  1 are > 0 , so we return x.

NOW, THE OUTPUT LAYER

In [298]:
x4=(hidden_layer*weights['x4']).sum()

In [299]:
x4=sigmoid(x4)

In [300]:
output_layer=array([x4])

In [301]:
output_layer

array([1])

Since, (x4=9) > 0, return 1