In [29]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

1. CREATE INPUT LAYER

In [30]:
data=array([2,3])

In [31]:
x0=data[0]
x1=data[1]

In [32]:
in_layer=array([x0,x1])

In [33]:
in_layer

array([2, 3])

2. CREATE HIDDEN LAYER

In [34]:
weights={'x2':array([1,1]),
         'x3':array([-1,1]),
         'x4':array([-2,1]),
         'x5':array([1,0]),
         'x6':array([1,-1])}

 CREATE 1st HIDDEN LAYER

In [35]:
x2=(in_layer*weights['x2']).sum()

In [36]:
x3=(in_layer*weights['x3']).sum()

In [37]:
hidden_layer1=array([x2,x3])
hidden_layer1

array([5, 1])

 CREATE  2nd HIDDEN LAYER

In [38]:
x4=(hidden_layer1*weights['x4']).sum()

In [39]:
x5=(hidden_layer1*weights['x5']).sum()

In [40]:
hidden_layer2=array([x4,x5])
hidden_layer2

array([-9,  5])

3. CREATE OUTPUT LAYER

In [41]:
x6=(hidden_layer2*weights['x6']).sum()

In [42]:
out_layer=array([x6])
out_layer

array([-14])