In [97]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [98]:
def relu(x):
    return max(0,x)

In [99]:
def sigmoid(x):
    if x<=0:
        return 0
    else:
        return 1
    

For Input layer

In [100]:
data=array([2,3])

In [101]:
x0=data[0]
x1=data[1]

In [102]:
in_layer=array([x0,x1])

In [103]:
in_layer

array([2, 3])

Assign weights to hidden layers

In [104]:
weights={'x2':array([1,1]),
         'x3':array([-1,1]),
         'x4':array([-2,1]),
         'x5':array([1,0]),
         'x6':array([1,-1])}

Hidden layer 1

In [105]:
x2=(in_layer*weights['x2']).sum()

In [106]:
x3=(in_layer*weights['x3']).sum()

In [107]:
x2=relu(x2)
x3=relu(x3)

In [108]:
hidden_layer1=array([x2,x3])
hidden_layer1

array([5, 1])

Hidden layer 2

In [109]:
x4=(hidden_layer1*weights['x4']).sum()

In [110]:
x5=(hidden_layer1*weights['x5']).sum()

In [111]:
x4=relu(x4) # or sigmoid activation
x5=relu(x5)

In [112]:
hidden_layer2=array([x4,x5])
hidden_layer2

array([0, 5])

output = [1,1] if we use both sigmoid functions(x4 ,x5)

......................

Now, the output layer

In [113]:
x6=(hidden_layer2*weights['x6']).sum()

In [114]:
x6=sigmoid(x6)

In [115]:
out_layer=array([x6])
out_layer

array([0])